# Generated by Django 2.2.2 on 2019-06-14 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tn', models.CharField(max_length=255, unique=True)),
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tcreatetime', models.DateField()),
                ('service_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('ticket_state_name', models.CharField(max_length=255)),
                ('queue_name', models.CharField(max_length=255)),
                ('artsubject', models.CharField(max_length=255)),
                ('artbody', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('auto_close', models.DateField()),
                ('closed', models.DateField()),
                ('moved_count', models.IntegerField(default=0)),
                ('first_line_emergence_time', models.DateField()),
                ('first_move_or_lock_time', models.DateField()),
                ('others_line_emergence_time', models.DateField()),
                ('others_line_lock_time', models.DateField()),
                ('others_line_message_time', models.FloatField()),
                ('auto_closed', models.FloatField()),
                ('forced_close', models.FloatField()),
                ('in_working_first', models.FloatField()),
                ('in_working_others', models.FloatField()),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Ticket')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
